### ISSUE TITLE
Question sur le logiciel

### ISSUE THREAD

**Issue by anthugo** [Skyrano/croissant-wallpaper#1]
Bonjour Monsieur Rameau,

Je voulais savoir si votre application fonctionnait avec les fonds d'ecran amouranth ?

C'est pour un ami.

bien à vous
Cordialement,
En l'attende de votre réponse
Anthotho développer en sémantique

**Comment by Skyrano** [comment]
Bonjour,
Cette application fonctionne avec tous les types de fichiers compatibles en tant que fond d'écran Windows.
Ainsi, peu importe le contenu du fichier tant que celui-ci est d'un type courant.
Pensez juste à modifier le fichier *config.yml* avec le chemin vers cette image (par exemple située à la racine de la clé USB).
Bien cordialement,
Alistair Rameau

**Comment by anthugo** [comment]
Merci Mr Skyrano... pour mon ami ;)
